# Strat-e-GPT Configuration File
# Race Strategy Prediction System

# Data Processing Settings
data:
  input_directory: "data"
  output_directory: "outputs"
  supported_formats: ["csv", "xlsx", "json"]
  max_missing_threshold: 0.5  # Maximum allowed missing values per row

# Machine Learning Settings
ml:
  test_size: 0.2
  random_state: 42
  cross_validation_folds: 5
  
  # Model Parameters
  random_forest:
    n_estimators: 100
    max_depth: 20
    min_samples_split: 2
    min_samples_leaf: 1
    
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 6
    min_samples_split: 2
    
  linear_regression:
    fit_intercept: true
    
  ridge_regression:
    alpha: 1.0

# Visualization Settings
visualization:
  default_figsize: [12, 8]
  dpi: 300
  style: "seaborn-v0_8"
  color_palette: "husl"
  
  # Plot Settings
  histogram_bins: 30
  correlation_cmap: "coolwarm"
  performance_colors:
    excellent: "green"
    good: "orange"
    poor: "red"

# Logging Settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/strat_e_gpt.log"
  max_file_size: "10MB"
  backup_count: 5

# Model Persistence
models:
  save_directory: "models"
  file_format: "pkl"
  include_metadata: true
  
# Performance Thresholds
performance:
  r2_excellent: 0.8
  r2_good: 0.6
  r2_poor: 0.4
  
  rmse_excellent: 0.1
  rmse_good: 0.2
  rmse_poor: 0.5

# Feature Engineering
features:
  categorical_encoding: "label"
  scaling_method: "standard"
  feature_selection_threshold: 0.01
  
# Data Validation
validation:
  min_rows: 100
  min_features: 3
  max_correlation_threshold: 0.95
  outlier_detection: true
  outlier_threshold: 3.0  # Standard deviations
